baseURL: "https://blog.sanfranciscan.org/"

disablePathToLower: true
languageCode: "en-us"

builddrafts: false
enableRobotsTXT: true

permalinks:
  post: ":year/:month/:day/:slug"
  fixed:  ":slug/"

theme: "lanyon-hugo"

Params:
  Author:           "Chema Hernández Gil"
  title:            "Chema Hernández Gil, A San Franciscan"
  tagline:          "Un poquito de todo"
  description:      "Writings and meditations by Chema Hernández Gil – organizer, foiled engineer, and media activist based in San Francisco."
  url:              "https://blog.sanfranciscan.org"
  baseurl:          '/'
  relme:            "https://sanfranciscan.org/@chema"
  DateForm:         "2006-01-02"
  StartYear:        "2000"
  google_site_verification: "Nibvm0oWeGTTEyp92lPF8SnPhHB2d8p8mJz2xc05ISA"

author:
  name:           "Chema Hernández Gil"
  url:            "https://social.sanfranciscan.org/@chema"

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 3

frontmatter:
  date:
  - :filename
  - :default
