baseURL: "https://sanfranciscan.org/"
canonifyURLs: true
title: "Chema Hernández Gil, A San Franciscan"
copyright: "© Chema Hernández Gil. All rights reserved."

outputs:
  home:
    - HTML
    - RSS

disablePathToLower: true
languageCode: "en-us"

builddrafts: false
enableRobotsTXT: true

permalinks:
  post: ":year/:month/:day/:slug"
  fixed:  ":slug/"

theme: "lanyon-hugo"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "About this Site"
      url: "/about/"
      weight: 2

    - name: "Your Correspondent"
      url: "/biography/"
      weight: 3

    - name: "Post Archive"
      url: "/post/"
      weight: 4

    - name: "Media Gallery"
      url: "/media/"
      weight: 5

    - name: "Kit & Gear"
      url: "/kit/"
      weight: 6

    - name: "Hardware"
      url: "/hardware/"
      weight: 7


Params:
  Author:           "Chema Hernández Gil"
  title:            "A San Franciscan"
  tagline:          "“Pueblo me llamo”"
  description:      "Writings and meditations by Chema Hernández Gil – organizer, foiled engineer, and media activist based in San Francisco."
  url:              "https://sanfranciscan.org"
  images:
    - "img/og-image.png"
  baseurl:          '/'
  relme:            "https://sanfranciscan.org/@chema"
  DateForm:         "2006-01-02"
  StartYear:        "1995"
  licenseUrl:       "https://sanfranciscan.org/license/"
  acquireLicensePage: "https://sanfranciscan.org/license"
  google_site_verification: "Nibvm0oWeGTTEyp92lPF8SnPhHB2d8p8mJz2xc05ISA"
  mainSections:
    - post
    - media
  authorDescription: "Chema Hernández Gil is a San Francisco–based labor organizer with an engineering background and roots in Mexico, Tennessee, and Switzerland, focused on labor, community, and media activism."
  sameAs:
    - "https://keyoxide.org/chema@sanfranciscan.org"
    - "https://social.sanfranciscan.org/@chema"
    - "https://ctrvx.net/chema"
    - "https://github.com/chema"
    - "https://www.linkedin.com/in/chemahdezgil"
    - "https://asanfranciscan.substack.com/"
    - "https://www.instagram.com/elsanfranciscano"
    - "https://x.com/elsanfranciscan"
    - "https://bsky.app/profile/chema.ctrvx.net"
    - "https://bsky.app/profile/chema.baysky.social"
    - "https://keybase.io/chema"
    
author:
  name:           "Chema Hernández Gil"
  url:            "https://social.sanfranciscan.org/@chema"

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 3

frontmatter:
  date:
  - :filename
  - :default

taxonomies:
  tag: tags