baseURL: "http://blog.sanfranciscan.org"
disablePathToLower: true
languageCode: "en-us"

builddrafts: false
enableRobotsTXT: true

permalinks:
  post: ":year/:month/:day/:slug"
  fixed:  ":slug/"

theme: "lanyon-hugo"

Params:
  title:            "A San Franciscan"
  tagline:          "Un poquito de todo"
  description:      "A collection of writings by a San Franciscan named Chema. Un poquito de todo."
  url:              "http://blog.sanfranciscan.org"
  baseurl:          ''
  DateForm:         "2006-01-02"

author:
  name:           'Chema Hernández Gil'
  url:            https://social.sanfranciscan.org/@chema

paginate:         3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 3

frontmatter:
  date:
  - :filename
  - :default
